[package]
name = "aula-app"
description = "Desktop app for controlling AULA keyboard RGB"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "keylux"
path = "src/main.rs"

[dependencies]
aula-protocol.workspace = true
aula-effects.workspace = true
anyhow.workspace = true
eframe.workspace = true
egui.workspace = true
rfd.workspace = true
tray-icon.workspace = true
raw-window-handle.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
